### ISSUE TITLE
Cannot open the application

### ISSUE THREAD

**Issue by ekardon** [xqemu/xqemu-manager#21] opened 2018-08-18 19:03 UTC
Hi, I am on Win 10 device and unable to run your application, as it exits with "Failed to execute script main".  I am using your latest AppVayor pre-build. What I got on the command line is:

`ModuleNotFoundError: No module named 'PyQt5.sip'`

I have PyQt5 and sip installed and latest. I didn't look at your code or recompiled but for the time being it doesn't work.

**Comment by mborgerson** [comment] 2018-10-09 21:02
Thank you for reporting this! Apparently it is a [known issue](https://stackoverflow.com/questions/51324754/python-3-6-x-pyinstaller-gives-error-no-module-named-pyqt5-sip) with [PyInstaller](https://github.com/pyinstaller/pyinstaller/issues/3630). We will need to change the distribution settings to force include PyQt5.sip to resolve this.

**Comment by thrimbor** [comment] 2018-10-10 01:02
Just tried reproducing the issue in a Windows 10 VM. It seems the only affected builds were the ones for the "ui: Force SDL display mode" commits. Everything newer or older seems to work fine (they also differ in size).
Since the PyInstaller bug is marked fixed and the builds aren't affected anymore, I suggest to close the issue.

**Comment by JayFoxRox** [comment] 2018-10-10 01:04
Will do. If everyone encounters this issue again, they can report here and we'll re-open it.

**Closed by JayFoxRox** 2018-10-10 01:04 UTC
